# 03 Train Image Model

Train EfficientNet-B0 with transfer learning for binary deepfake image classification.

In [1]:
from pathlib import Path

import pandas as pd
import torch
import torch.nn as nn
from PIL import Image, UnidentifiedImageError
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

DATA_ROOT = Path("../../data/raw/images")
MODEL_DIR = Path("../../models/image")
MODEL_PATH = MODEL_DIR / "new_best_model.pth"
SPLITS = ["train", "val", "test"]
CLASSES = ["real", "fake"]
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}
BATCH_SIZE = 32
NUM_WORKERS = 0
EPOCHS = 10
LEARNING_RATE = 0.0004029469429975904
DROPOUT_RATE = 0.4955353561591949

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [2]:
def collect_image_paths(data_root: Path) -> pd.DataFrame:
    rows = []
    for split in SPLITS:
        for class_name in CLASSES:
            class_dir = data_root / split / class_name
            print(f"Scanning {class_dir} | exists={class_dir.exists()}")
            if not class_dir.exists():
                continue
            for path in sorted(class_dir.iterdir()):
                if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
                    rows.append({"path": str(path), "split": split, "label": class_name, "label_id": 1 if class_name == "fake" else 0})
    return pd.DataFrame(rows)


df = collect_image_paths(DATA_ROOT)
print(f"Loaded records: {len(df)}")
display(df.head())
display(df.groupby(["split", "label"]).size().unstack(fill_value=0))

Scanning ..\..\data\raw\images\train\real | exists=True
Scanning ..\..\data\raw\images\train\fake | exists=True
Scanning ..\..\data\raw\images\val\real | exists=True
Scanning ..\..\data\raw\images\val\fake | exists=True
Scanning ..\..\data\raw\images\test\real | exists=True
Scanning ..\..\data\raw\images\test\fake | exists=True
Loaded records: 190335

                                             path  split label  label_id
0     ..\..\data\raw\images\train\real\real_0.jpg  train  real         0
1     ..\..\data\raw\images\train\real\real_1.jpg  train  real         0
2    ..\..\data\raw\images\train\real\real_10.jpg  train  real         0
3   ..\..\data\raw\images\train\real\real_100.jpg  train  real         0
4  ..\..\data\raw\images\train\real\real_1000.jpg  train  real         0

label   fake   real
split
test    5492   5413
train  70001  70001
val    19641  19787

In [3]:
train_transform = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)

eval_transform = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)


class DeepfakeImageDataset(Dataset):
    def __init__(self, dataframe: pd.DataFrame, transform=None):
        self.dataframe = dataframe.reset_index(drop=True)
        self.transform = transform
        print(f"Dataset initialized with {len(self.dataframe)} images")

    def __len__(self):
        return len(self.dataframe)

    def _load_image(self, path: str):
        try:
            with Image.open(path) as image:
                return image.convert("RGB")
        except (OSError, UnidentifiedImageError) as error:
            print(f"Warning: corrupted image replaced with blank tensor: {path} | {error}")
            return Image.new("RGB", (224, 224), color=(0, 0, 0))

    def __getitem__(self, index):
        row = self.dataframe.iloc[index]
        image = self._load_image(row["path"])
        label = torch.tensor(row["label_id"], dtype=torch.float32)
        if self.transform is not None:
            image = self.transform(image)
        return image, label

In [4]:
train_dataset = DeepfakeImageDataset(df[df["split"] == "train"], transform=train_transform)
val_dataset = DeepfakeImageDataset(df[df["split"] == "val"], transform=eval_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

print(f"Train size: {len(train_dataset)} | Val size: {len(val_dataset)}")
images, labels = next(iter(train_loader))
print(f"Debug train batch images: {images.shape}")
print(f"Debug train batch labels: {labels.shape}")
print(f"Debug train labels: {labels[:10].tolist()}")

Dataset initialized with 140002 images
Dataset initialized with 39428 images
Train size: 140002 | Val size: 39428
Debug train batch images: torch.Size([32, 3, 224, 224])
Debug train batch labels: torch.Size([32])
Debug train labels: [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

In [5]:
def build_model() -> nn.Module:
    weights = models.EfficientNet_B0_Weights.IMAGENET1K_V1
    model = models.efficientnet_b0(weights=weights)
    in_features = model.classifier[1].in_features
    # Replace classifier with dropout and linear layer
    model.classifier = nn.Sequential(
        nn.Dropout(p=DROPOUT_RATE),
        nn.Linear(in_features, 1)
    )
    return model


model = build_model().to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=1e-4
)

print(model.classifier)
print(f"Model output units: {model.classifier[1].out_features}")

Sequential(
  (0): Dropout(p=0.4955353561591949, inplace=False)
  (1): Linear(in_features=1280, out_features=1, bias=True)
)
Model output units: 1

In [6]:
def run_epoch(model, loader, criterion, optimizer=None, phase="train"):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    with torch.set_grad_enabled(is_train):
        for batch_idx, (images, labels) in enumerate(loader):
            images = images.to(device)
            labels = labels.to(device).unsqueeze(1)

            if batch_idx == 0:
                print(f"{phase} batch images shape: {images.shape}")
                print(f"{phase} batch labels shape: {labels.shape}")

            logits = model(images)
            loss = criterion(logits, labels)

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                # Gradient clipping for stability
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

            probabilities = torch.sigmoid(logits)
            predictions = (probabilities >= 0.5).float()

            if batch_idx == 0:
                print(f"{phase} logits: {logits[:5].detach().cpu().view(-1).tolist()}")
                print(f"{phase} probabilities: {probabilities[:5].detach().cpu().view(-1).tolist()}")
                print(f"{phase} predictions: {predictions[:5].detach().cpu().view(-1).tolist()}")

            batch_size = images.size(0)
            running_loss += loss.item() * batch_size
            correct += (predictions == labels).sum().item()
            total += batch_size

    epoch_loss = running_loss / max(total, 1)
    epoch_accuracy = correct / max(total, 1)
    return epoch_loss, epoch_accuracy

In [7]:
MODEL_DIR.mkdir(parents=True, exist_ok=True)
best_val_loss = float("inf")
history = []

print(f"LR: {LEARNING_RATE}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Dropout: {DROPOUT_RATE}")

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

for epoch in range(1, EPOCHS + 1):
    print(f"\nEpoch {epoch}/{EPOCHS}")
    train_loss, train_accuracy = run_epoch(model, train_loader, criterion, optimizer, phase="train")
    val_loss, val_accuracy = run_epoch(model, val_loader, criterion, optimizer=None, phase="val")
    
    scheduler.step()

    history.append(
        {
            "epoch": epoch,
            "train_loss": train_loss,
            "train_accuracy": train_accuracy,
            "val_loss": val_loss,
            "val_accuracy": val_accuracy,
        }
    )

    print(
        f"Epoch {epoch}: "
        f"train_loss={train_loss:.4f}, train_acc={train_accuracy:.4f}, "
        f"val_loss={val_loss:.4f}, val_acc={val_accuracy:.4f}"
    )

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), MODEL_PATH)
        print(f"Saved best model to {MODEL_PATH} with val_loss={best_val_loss:.4f}")

history_df = pd.DataFrame(history)
display(history_df)

LR: 0.0004029469429975904
Batch size: 32
Dropout: 0.4955353561591949

Epoch 1/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-0.18099159002304077, -0.4496857523918152, 0.3786068558692932, 0.5699411034584045, -0.10021071881055832]
train probabilities: [0.4548751711845398, 0.3894354999065399, 0.5935370326042175, 0.6387495994567871, 0.4749682545661926]
train predictions: [0.0, 0.0, 1.0, 1.0, 0.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-9.124555587768555, -11.736320495605469, -1.9171425104141235, -16.328744888305664, -8.786541938781738]
val probabilities: [0.00010894531442318112, 7.997923603397794e-06, 0.12818054854869843, 8.100580828340753e-08, 0.00015275202167686075]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 1: train_loss=0.0684, train_acc=0.9746, val_loss=0.1731, val_acc=0.9557
Saved best model to ..\..\models\image\new_best_model.pth with val_loss=0.1731

Epoch 2/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-10.050107955932617, -10.173023223876953, -8.935098648071289, -4.36130428314209, -14.792543411254883]
train probabilities: [4.317922139307484e-05, 3.818524783127941e-05, 0.00013166754797566682, 0.012600922957062721, 3.7642618622157897e-07]
train predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-8.967156410217285, -9.07216739654541, -0.581964373588562, -12.238930702209473, 0.1746702492237091]
val probabilities: [0.00012751405301969498, 0.00011480422836029902, 0.3584807217121124, 4.838355835090624e-06, 0.5435568690299988]
val predictions: [0.0, 0.0, 0.0, 0.0, 1.0]
Epoch 2: train_loss=0.0396, train_acc=0.9851, val_loss=0.0581, val_acc=0.9807
Saved best model to ..\..\models\image\new_best_model.pth with val_loss=0.0581

Epoch 3/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-9.118361473083496, 8.638606071472168, -11.143345832824707, 10.626606941223145, -13.695084571838379]
train probabilities: [0.0001096221458283253, 0.9998229146003723, 1.447105205443222e-05, 0.9999756813049316, 1.127976020143251e-06]
train predictions: [0.0, 1.0, 0.0, 1.0, 0.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-10.879444122314453, -8.86140251159668, -3.1844143867492676, -8.738667488098145, -4.971408367156982]
val probabilities: [1.884123048512265e-05, 0.00014173601812217385, 0.03975646570324898, 0.00016024161595851183, 0.006885635666549206]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 3: train_loss=0.0311, train_acc=0.9879, val_loss=0.0653, val_acc=0.9800

Epoch 4/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [23.4591121673584, -11.178205490112305, -14.128159523010254, 15.05860424041748, 17.068567276000977]
train probabilities: [1.0, 1.3975294677948114e-05, 7.315061338886153e-07, 0.9999997615814209, 1.0]
train predictions: [1.0, 0.0, 0.0, 1.0, 1.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-10.82451057434082, -10.028595924377441, -1.0556056499481201, -16.204790115356445, -5.3715643882751465]
val probabilities: [1.990518103411887e-05, 4.411811460158788e-05, 0.2581501007080078, 9.169571768552487e-08, 0.0046253628097474575]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 4: train_loss=0.0253, train_acc=0.9899, val_loss=0.0521, val_acc=0.9845
Saved best model to ..\..\models\image\new_best_model.pth with val_loss=0.0521

Epoch 5/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [6.482876300811768, 7.661463260650635, 3.558889627456665, -12.764678955078125, -13.072245597839355]
train probabilities: [0.9984728693962097, 0.9995296001434326, 0.9723177552223206, 2.8600202313100453e-06, 2.1027854018029757e-06]
train predictions: [1.0, 1.0, 1.0, 0.0, 0.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-14.782124519348145, -12.277289390563965, -3.2173268795013428, -14.232341766357422, -10.145686149597168]
val probabilities: [3.803686468017986e-07, 4.656278633774491e-06, 0.038518864661455154, 6.591317287529819e-07, 3.9243470382643864e-05]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 5: train_loss=0.0197, train_acc=0.9918, val_loss=0.0547, val_acc=0.9845

Epoch 6/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [24.103317260742188, -17.59257698059082, -16.71408462524414, -10.735569953918457, 2.3258581161499023]
train probabilities: [1.0, 2.288974165765012e-08, 5.510173650691286e-08, 2.1756637579528615e-05, 0.91099613904953]
train predictions: [1.0, 0.0, 0.0, 0.0, 1.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-14.319620132446289, -11.224666595458984, -4.909753322601318, -16.804468154907227, -4.503480434417725]
val probabilities: [6.040427820153127e-07, 1.3340848454390652e-05, 0.007320323958992958, 5.0339885149242036e-08, 0.010949186980724335]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 6: train_loss=0.0151, train_acc=0.9939, val_loss=0.0497, val_acc=0.9863
Saved best model to ..\..\models\image\new_best_model.pth with val_loss=0.0497

Epoch 7/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-13.618197441101074, 14.747225761413574, -16.07402229309082, -8.358731269836426, 14.257311820983887]
train probabilities: [1.2181238844277686e-06, 0.9999996423721313, 1.0450588661115034e-07, 0.00023428656277246773, 0.9999994039535522]
train predictions: [0.0, 1.0, 0.0, 0.0, 1.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-17.12804412841797, -12.797832489013672, -4.856769561767578, -18.18677520751953, -14.811566352844238]
val probabilities: [3.642377421897436e-08, 2.766755414995714e-06, 0.007715569343417883, 1.2635251955828153e-08, 3.6933315072928963e-07]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 7: train_loss=0.0108, train_acc=0.9955, val_loss=0.0677, val_acc=0.9863

Epoch 8/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-18.77083969116211, 13.417845726013184, 13.707353591918945, -24.501846313476562, 18.82196044921875]
train probabilities: [7.045760863633177e-09, 0.9999985694885254, 0.999998927116394, 2.2855110165531656e-11, 1.0]
train predictions: [0.0, 1.0, 1.0, 0.0, 1.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-20.280282974243164, -13.604409217834473, -7.809904098510742, -18.824140548706055, -13.456110954284668]
val probabilities: [1.5573456968454025e-09, 1.2350359384072362e-06, 0.00040553242433816195, 6.680048958429552e-09, 1.4324671155918622e-06]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 8: train_loss=0.0081, train_acc=0.9968, val_loss=0.0646, val_acc=0.9878

Epoch 9/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [14.290019035339355, -14.221631050109863, -15.52102279663086, -12.308764457702637, -7.404456615447998]
train probabilities: [0.9999994039535522, 6.662294254056178e-07, 1.8167926896239806e-07, 4.5120050344849005e-06, 0.0006081645842641592]
train predictions: [1.0, 0.0, 0.0, 0.0, 0.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-16.853679656982422, -12.800760269165039, -8.877204895019531, -16.943754196166992, -13.051939964294434]
val probabilities: [4.79225477079126e-08, 2.7586668238654966e-06, 0.00013951415894553065, 4.37946496845143e-08, 2.145920234397636e-06]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 9: train_loss=0.0052, train_acc=0.9980, val_loss=0.0664, val_acc=0.9879

Epoch 10/10
train batch images shape: torch.Size([32, 3, 224, 224])
train batch labels shape: torch.Size([32, 1])
train logits: [-26.548049926757812, -41.43537902832031, 11.05433177947998, 16.38840103149414, 18.86634063720703]
train probabilities: [2.9534419614812846e-12, 1.0112150639562755e-18, 0.9999841451644897, 0.9999998807907104, 1.0]
train predictions: [0.0, 0.0, 1.0, 1.0, 1.0]
val batch images shape: torch.Size([32, 3, 224, 224])
val batch labels shape: torch.Size([32, 1])
val logits: [-17.80919075012207, -13.685726165771484, -9.590510368347168, -19.04624366760254, -15.270547866821289]
val probabilities: [1.8431757453640785e-08, 1.138581637860625e-06, 6.83698381180875e-05, 5.349602094639749e-09, 2.333915887220428e-07]
val predictions: [0.0, 0.0, 0.0, 0.0, 0.0]
Epoch 10: train_loss=0.0040, train_acc=0.9984, val_loss=0.0712, val_acc=0.9881

   epoch  train_loss  train_accuracy  val_loss  val_accuracy
0      1    0.068397        0.974579  0.173092      0.955666
1      2    0.039594        0.985122  0.058130      0.980699
2      3    0.031149        0.987922  0.065322      0.980014
3      4    0.025313        0.989900  0.052058      0.984453
4      5    0.019675        0.991772  0.054717      0.984529
5      6    0.015074        0.993907  0.049736      0.986304
6      7    0.010754        0.995543  0.067738      0.986330
7      8    0.008081        0.996757  0.064584      0.987801
8      9    0.005155        0.997950  0.066378      0.987902
9     10    0.003968        0.998429  0.071219      0.988105